name: Trail Run

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: cloning the github repo to runner
        uses: actions/checkout@4

      - name: access the varibles
        run: |
          echo "${{ vars.ADMINPASSWORD }}"
